circleci/circleci-images

- .gitignore
- Makefile
- android/Dockerfile.m4
- android/generate-images
This change adds a new target to the makefile to generate
android/images/api-25-alpha/Dockerfile
which is a Dockerfile that generates a CircleCI blessed image for
running Android builds. I have alpha in the tag name so that we can
iterate on the container image.
I have punted on generating other Android API levels for now, until we
can see how this is working with customers.
> Generate Android SDK 25 image

- shared/images/build.sh
Remove images after running `docker push` to prevent images with many
tags from running out of disk space.
> [Build] Remove images after pushing

- shared/images/Dockerfile-basic.template
We weren't able to start this workflow.
Job "publish_android" has filters configured in the job definition. These filters are incompatible with workflows. [...]
See the [CircleCI Discuss topic](https://discuss.circleci.com/t/cant-run-workflow-at-circleci-images-fork/14788).
This setting allows insecure operations, including [installing unauthenticated packages](https://github.com/Debian/apt/blob/master/apt-private/private-download.cc#L81). It is also deprecated.
I tested the remove of this setting in our own build image.
Removed `APT::Get::force-Yes`.
> Don't use `--force-yes` for `apt-get` => insecure actions

- ruby/generate-images
This PR relates to an issue where node was no longer being installed on the Ruby images.
Node pushed an update to their metadata that adds an additional Architecture line (or reorders the output). My change greps one additional line for a given tag, giving us sufficient data to pull in their Dockerfile.
> Node added an Architecture field; we need one more line

- .circleci/config.yml
- openjdk/generate-images
- openjdk/java_helper
- php/generate-images
- shared/images/Dockerfile-basic.template
- shared/images/Dockerfile-browsers.template
- shared/images/refresh-tools-cache
A bit of a giant PR in order to get circleci-images green.
Lots of failures are due to hitting the GitHub/BitBucket API rate limits.  Instead of relying on that to download latest, let's cache them in S3 and download from there.  Notice that I'm using `latest` here instead of a concrete version.  I have considered using concrete versions so it's easy for us to switch back.  However, given that we don't pin versions now and always use latest, and users desiring to pin can always lookup the actual github url 
Also, fix SBT again :(.  SBT 0.13.6 was released and updated in GitHub without the zipfiles in https://github.com/sbt/sbt/releases - as of yet.  Therefore let's just download it from the SBT website link.
Lastly, noticed that OpenJDK dockerfile inserts the building container `PATH`! …
> Cache tools And Other stuff

- php/generate-images
PHP Builds are failing for the rc/beta tags.
Xdebug tools don't support RC/beta releases yet:
```
checking whether to enable Xdebug support... yes, shared
checking Check for supported PHP versions... configure: error: not supported. Need a PHP version >= 5.5.0 and < 7.2.0 (found 7.2.0beta2)
ERROR: `/tmp/pear/temp/xdebug/configure --with-php-config=/usr/local/bin/php-config' failed
The command '/bin/sh -c mkdir -p /etc/php && pecl install xdebug && echo 'zend_extension="/usr/local/lib/php/extensions/no-debug-non-zts-20160303/xdebug.so"' > /etc/php/xdebug.ini' returned a non-zero code: 1
make[1]: *** [php/images/rc/publish_image] Error 1
```
> PHP: don't support RC/beta releases

- shared/images/build.sh
- shared/images/generate.sh
A single official image may have multiple tags.  Currently, `7.1.8-fpm` is aliased to `7.1-fpm, 7-fpm, fpm` - and this results into independent docker image builds for each of these tags.  We rely on cache to speed up builds but our build scripts is aggressive in deleting caches for variants and the like, causing real independent builds.
This PR speeds up builds and ensure that we build a single image and tag it multiple times eliminate the chance of the tags being slightly out of sync.
Frequently official images use many aliases (e.g. latest).  Build image
once and tag aliases instead of building multiple times and assuming
Docker cache will sort it out.
The implementation uses a TAG and ALIASES file on the generated paths.
TAG contains the canonical tag.  ALIASES contains comma …
> Build image once and tag aliases

- shared/images/Dockerfile-browsers.template
This PR addresses the lack of Java in the browsers images. Users were previously installing it manually or building custom images extending this one just for Java.
We are now installing openjdk-7-jre for all images requiring browsers.
> Install Java in the browsers image

- android/Dockerfile.m4
Fixes #72
Adding `ruby` to the base Android install, since we expect most Android projects to deploy to the Google Play store using Fastlane.
> Install Ruby 2.4 in Android image

- android/Dockerfile.m4
Also install bundler by default so that users can simply `bundle install`
whatever they need.
Before this change, users would need to `sudo gem install` and `sudo bundle install` things, which is nasty.
> Install gems as user by default

- php/generate-images
- [x ] I've run `make` from the root directory to see all Dockerfiles are created successfully.
- [x ] I've updated the documentation if necessary. (not necessary in this update)
This PR is not related to an existing issue, its related to an issue I encountered while trying to setup phpunit with coverage text.
The change is required, because xdebug is not correctly enabled, so the coverage drivers where not found and it was not showing on `phpinfo()` output or `php -i`.
Initially built image 7.1.9-cli and ssh'd into it, tried installing and enabling xdebug, to find out that it was indeed installed, just not enabled. Enabled it using the `docker-php-ext-enable` command provided by the php docker image (our base) and got expected result from `php -i` and running `phpunit` on my project.
It …
> use docker-php-ext-enable command to enable xdebug

- android/Dockerfile.m4
- android/generate-images
_I've run `generate-images` in the `android` directory and `docker build .` from `android/images/api-27-alpha` successfully. Can do this whole step if you want.
Android API 27 is out, as well as Build Tools 27.0.0. We'd like to use these in our project.
Based on https://github.com/circleci/circleci-images/pull/88, I've added the new Build Tools, and I've added 27 to the list of API version that images are generated for.
> Add support for API 27

- shared/images/generate-node.sh
Fixes #95 
Pinning the NodeJS version used in `-node` variants to the current NodeJS LTS release. Pinning the major and minor version. Point releases will be updated regularly.
The current LTS release is NodeJS v8.9.0. Pinning to `node/8.9`.
> Switch Node Docker tag from latest to '8.9'for Node variants.

- ruby/generate-images
This PR relates to #98.
On Ruby versions < 2.5, bundler 1.16.0 is pre-installed on the upstream images, which has a breaking change affecting some % of users.
We should pin bundler to a stable version to avoid breaking peoples builds, which will our users time and our support team tickets.
Using `IMAGE_CUSTOMIZATIONS` allows us to hook into the Dockerfile generator to append some commands. In this case we want to uninstall bundler 1.16 and install the stable version 1.15.4.
I've downloaded the Dockerfiles from a successful build and tested the images. Everything works except the 2.5 preview image because the way Ruby packages bundler as a default gem, in the standard library, it can't be removed so easily.
> Downgrade bundler to 1.15.4 as 1.16 has a breaking change

- ruby/generate-images
```
gem install bundler
Fetching: bundler-1.16.0.gem (100%)
ERROR:  While executing gem ... (Errno::EACCES)
Permission denied @ rb_sysopen - /usr/local/bundle/cache/bundler-1.16.0.gem
```
cc #99
This PR relates to <issue>.
> Fixes an issue where installing on top of this requires sudo

- mongo/generate-images
I'm not sure why these exist.. but they fail to build.
There's probably a better solution to this.
> Filter shared tags from mongo

- ruby/generate-images
This reverts https://github.com/circleci/circleci-images/pull/99 as it was not
correctly removing and cleaning up Bundler versions.
The Ruby has not been published in a while due to a bug with tag handling, so
this was missed before today.
If someone wants to use a specific bundler version, they should install it
themselves and use bundlers mechanisms for handling that.
> Revert bundler pinning

- openjdk/generate-images
OpenJDK 9 images have empty cacert files which was reported in
https://github.com/docker-library/openjdk/issues/145 and http://bugs.java.com/view_bug.do?bug_id=8189357 .
Here we use a cacert cache from `openjdk:9-slim` image that seems to be
populated correctly.
> Use JDK 9-slim cacerts for OpenJDK 9

- php/generate-images
- shared/images/build.sh
Docker builds may fail for many transient failures (e.g. networking
blips, origin server returning 500, etc).  Here we retry the docker
build one more time.
This shouldn't add much overhead in the true failure case: Only the last
failed step would be re-run as earlier steps should be cached.
A sample transient failure is connection to pgp.mit.edu timing out in https://circleci.com/gh/circleci/circleci-images/3491 :
```
+ gpg --keyserver pgp.mit.edu --recv-keys 94AE36675C464D64BAFA68DD7434390BDBE9B9C5
gpg: directory '/root/.gnupg' created
gpg: keybox '/root/.gnupg/pubring.kbx' created
gpg: keyserver receive failed: No data
+ gpg --keyserver keyserver.pgp.com --recv-keys 94AE36675C464D64BAFA68DD7434390BDBE9B9C5
gpg: keyserver receive failed: Connection timed out
+ gpg --keyserver …
```
> Attempt to recover from transient build fails

- shared/images/Dockerfile-basic.template
Some images (i.e. php) use debian stretch-slim which doesn't have some
man directories causing installs to fail.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=863199
This hit build https://circleci.com/gh/circleci/circleci-images/3536
> Create man directory

- .circleci/config.yml
- shared/images/generate.sh
PHP images take ~2 hours, buildpacks and python images over an hour.
Thus lets parallelize them
> Parallelize expensive images

- .gitignore
- shared/images/Dockerfile-browsers.template
- [n/a] I've updated the documentation if necessary.
This PR relates to issue #125.
- adds geckodriver to all `-browsers` images
- tested `jq`, `curl`, geckodriver syntax locally
- ran `make` to ensure Dockerfiles can be created successfully
- curl GitHub API to get latest `linux64` geckodriver release
- download latest `linux64` geckodriver release
- move to `/usr/local/bin` & test version #
> Iynere add geckodriver

- .circleci/config.yml
- README.md
- there's currently no easy way for customers to view dockerfiles for our convenience images
- sending them into the build artifacts for this repo is needlessly complicated
- we can't work with docker hub's automated builds with integrated dockerfiles for a variety of reasons
- i set up a [separate repository](https://github.com/circleci-public/circleci-dockerfiles) solely to store dockerfiles for our convenience images.
- (if everything had worked on first push, there wouldn't be anything in that repo yet, but, since i messed up some conditionals before [this commit](https://github.com/circleci/circleci-images/pull/127/commits/dc12426f5fab795286ea8218d778bc8867e22cb0), [circleci-dockerfiles](https://github.com/circleci-public/circleci-dockerfiles) now nicely demonstrates the intended …
> initial work: push Dockerfiles to separate GitHub repo for customer convenience

- shared/images/refresh-tools-cache
SBT download is failing https://circleci.com/gh/circleci/circleci-images/4072 because the latest SBT release is an RC release without any binary tarballs included: https://api.github.com/repos/sbt/sbt/releases/8938949 .
This instead attempts to find the most recent production release with binary tarballs that's not an RC or a milestone release.  Sadly, I cannot think of a better way for finding "production" releases.
> Find the latest production release of SBT

- shared/images/README-basic.template
While reading the documentation on the dockerhub for node I noticed some grammatical bits that could be cleaned up.
Tightened up the wording, changed `suite` to `suit`.
> Correct some typos in the README template

- mongo/resources/Dockerfile-ram.template
This PR relates to and fixes #143 . See that issue for a full description of the bug. However, this PR is able to fix the issue in an even simpler way than described in the issue, while also resolving an outstanding "TODO" in the existing Dockerfile.
I've tested this by building and running all of the `-ram` images (3.0, 3.2, 3.4, 3.6) locally. Without this PR, all of the `-ram` images except 3.6 crash when they are run.
In `mongo:3.6`, there is only a file at `/usr/local/bin/docker-entrypoint.sh`. In earlier versions, there is also a symlink at `/entrypoint.sh`.
Previously, the attempt to edit the symlink without `sed`'s `--follow-symlinks` option was causing the symlink to be rewritten as a real file.
By now ignoring the symlink and only editing the real file. both 3.6 and pre-3.6 …
> Only edit the real mongo entrypoint file

- android/Dockerfile.m4
- ~~[ ] I've updated the documentation if necessary.~~
Refs flutter/flutter#14239
Verified by successfully running `flutter test` inside of the modified circleci/android:api-27-alpha Docker image
Install common OpenGL libraries so that [Flutter](https://flutter.io) can run unit tests in headless mode under CircleCI's Android images
> Ensure that libglu exists for Flutter test

- php/generate-images
This PR relates to https://github.com/circleci/circleci-images/issues/148
Xdebug should be compatible with 7.2 now.
> Re-introduce xdebug

- php/generate-images
> PHP5 no longer supports xdebug

- openjdk/generate-images
This PR relates to https://github.com/circleci/circleci-images/issues/171
Installing openjfx in our openjdk images.
> Install openjfx

- shared/images/Dockerfile-browsers.template
Headless browser testing isn't working with Chrome 65.0.3325.146-1 so we're reverting and pinning to 64.0.3282.186-1.
> Pin Chrome to 64.0.3282.186-1 to address browser testing issues

- android/Dockerfile.m4
This makes the circle-android program executable. It's required due to changes in the way the program is copied into the image.
I've tested to confirm that images built with this change do indeed have the circle-android binary runnable as the circleci user.
> Ensure circle-android is runnable

- .circleci/config.yml
I propose that production images should be built nightly instead of only on Sundays. I actually thought this was what we were doing.
Issue #180 is exactly why images should be built more often rather than less often. Security releases not only happen for multiple supported releases of a single language such as Ruby, but then across many of the languages we support and any dependencies in those images that we may not be aware of.
> Switch to nightly image builds.

- shared/images/Dockerfile-browsers.template
The version of Chrome that we locked builds to is no longer hosted by Google. This is causing builds to fail. Switching to the current release.
> Revert Chrome download to current release.

- golang/generate-images
https://github.com/golang/dep has been widely adopted as the most common way of managing `vendor` in Go. Including it in the circleci image allows users to download dependencies (if they are not already checked into git) or validate that PRs have updated `vendor` correctly according to the contents of `Gopkg.toml/lock`.
Add another `RUN` line to download `dep`.
> Add dep to golang image

- buildpack-deps/resources/Dockerfile-dind.template
`buildpack-deps` images are failing. In trying to locate the error, I noticed a bunch of errors about installing the `btrfs-tools` package.
In newer distro releases, that package has been replaced by `btrfs-progs`. Some distros such as Ubuntu 18.04 has both packages with the formal being a meta transitional package. That works. Debian Sid has no such thing though so installing `btrfs-tools` is failing.
I made a new RUN command try try installing one or then the other. This should help with the transition period. Once we're no longer building the old distros, we can remove the installation of `btrfs-tools` all together.
My only concern, is the way Docker layers are cached going to affect this at all? For example, could the RUN command install `btrfs-progs` and get cached, and then when …
> Fix buildpack-deps image btrfs package.

- shared/images/manifest
"Many applications refuse to run as run": this should be "run as root".
> Fix typo in manifest

- android/generate-images
Adds an `android-28` image for targeting Android P (the [APIs are final as of today](https://android-developers.googleblog.com/2018/06/android-p-beta-2-and-final-apis.html))
> Add android 28 platform

- postgres/resources/Dockerfile-postgis.template
Fixes #211.
This PR relates to https://github.com/circleci/circleci-images/issues/211.
The execution method of additional scripts in the Postgres entrypoint was changed, executable scripts are now executed in a subshell instead of sourcing them. This leads to the environment variable `psql` not being visible.
Non-executable scripts on the other hand get sourced.
See also:
https://github.com/docker-library/postgres/pull/452
The change makes the additional script non-executable so that the entrypoint sources it instead of executing it.
> Postgres: remove executable flag from postgis init so that the entrypoint sources it, fixes #211

- php/generate-images
This PR relates to https://github.com/CircleCI-Public/circleci-dockerfiles/issues/9.
Many modern PHP tools expect zip and intl extensions.  Our docs and users are having to run these installs during CI/CD which is slowing them down, and costing us extra compute time/resources.
docker 
```
$ cd php/images/7.2.7-apache-stretch/
$ docker build . -t php-test
Successfully built 3e2acf650f6b
circleci@c2183dd5a6ae:/var/www/html$ php -m | grep 'intl\|zip'
intl
zip
```
This adds additional `docker-php-ext-` commands to install `zip` and `intl` modules.  Additionally runs a apt-get install to install the icu and zip libraries needed.
> add intl and zip to PHP images issue 9 in public

- golang/generate-images
Adding the Node.js variant to the Go bundle. There's no reason that only a few language images shouldn't have it. Consistency is likely best here.
> Add Node variant to Go bundle.

- android/Dockerfile.m4
This PR relates to #228 - the `Android NDK` is not properly extracted. The build process expects to find the NDK tools directly inside `ANDROID_NDK_HOME` but the extract process puts them in a subdirectory of `ANDROID_NDK_HOME`.
Before I made this change all my builds (of an android project) were failing with an `NDK is missing a "platforms" directory.` message. After I added a job step that manually copies the content of the ndk subdirectory to the ndk directory itself all build were successful.
The added support for `Android NDK` relies on a downloaded `.zip` file that is extracted and its content used for NDK builds. The problem in the mentioned issue is that the extracted content is actually unzipped in a subdirectory inside the `ANDROID_NDK_HOME`. E.g. if `ANDROID_NDK_HOME` is …
> Properly extract the Android NDK from the downloaded archive

- .circleci/config.yml
currently, we rebuild all images on any commit to any part of the repo. we can save ourselves a lot of time if we only build images when code that touches them has changed. because the repos are interconnected, this _isn't_ as simple as simply `grep`'ing the `git diff` for the name of the repo—but it's _almost_ that simple.
for each `publish_image` job, check the `git diff` for the current commit & only proceed with the job if:
- the directory for that image itself has changed
- the `/shared` directory has changed
- the Makefile has changed
(list could arguably be expanded to include the config.yml file itself, but that would also have drawbacks)
> git diff logic

- .circleci/config.yml
we probably want to build all images always on master, even if no files related directly to a particular `$PLATFORM` have been modified
add a branch check to our `git diff` logic
> always build all images on master

- .circleci/config.yml
This PR relates to #243 
rather than always building all images on any commit (to branches that are part of the build/publish control flow), only build when the requisite `$PLATFORM`, or the makefile, or any of the `/shared` shell scripts, are modified.
it's working on staging ! https://circleci.com/workflow-run/a9943633-4e57-43c2-9647-ecff459e36a2
> only build images when necessary

- shared/images/Dockerfile-browsers-legacy.template
This PR relates to failing builds we're seeing with regards to phantomjs.
> Fix the failing builds by setting OPENSSL_CONF to anything

- android/Dockerfile.m4
Version 28.0.3 is required for Android Gradle Plugin 3.2.x.
Closes CircleCI-Public/circleci-dockerfiles#13.
> Add Android SDK Build Tools 28.0.3

- shared/images/generate-node.sh
This PR relates to an issue where certain images are extending the wrong base image.
> Remove the second FROM line that is breaking images

- php/generate-images
This PR relates to this Discuss thread:
https://discuss.circleci.com/t/docker-php-ext-install-error-exited-with-123-directory-nonexistent/26786
There was a breaking change upstream in the PHP docker-php-ext-enable script that requires an environment variable only accessible to the main user. This change allows us to persist the required env var to the sudo shell without requiring the use of the -E on sudo.
> Persist the PHP_INI_DIR env var to avoid sudo -E

- openjdk/generate-images
This PR relates to an issue where we are pulling in oraclelinux images and wrongfully assuming apt is installed.
> Exclude oraclelinux from the openjdk build

- dynamodb/resources/Dockerfile-basic.template
This PR relates to an issue where newer versions of Dynamodb are failing to build because wget is missing.
> Fall back to curl when wget is missing

- shared/images/generate-node.sh
The Node LTS has been bumped from Node.js v8 to v10. We're a few weeks behind on this but this completes that update on our end.
> Updating Node variants to current LTS, 10.

- .circleci/config.yml
=### Checklist
all the image-publishing jobs here failed: https://circleci.com/workflow-run/cca89a03-09b2-47c3-9255-0e7a89aa9417
whereas almost all of these all passed: https://circleci.com/workflow-run/94e7d232-6c09-4dfa-b5ac-8c08673e8925
because the compare-url orb doesn't account for scheduled workflows very well (https://github.com/iynere/compare-url-orb/issues/5)
luckily, we always want to build all nightly images, so this just modifies the config using some 2.1 syntax to only use the compare-url orb on commit-based workflows
we also had some redundant branch filters in our workflows config syntax
PR'ing directly against master b/c without this, all our nightlies will continue to fail, whereas we have some additional changes in staging that we want to sit on for at least week or so
> only use compare-url orb in commit-triggered workflows

- .circleci/config.yml
trying to set goss env vars using circle's default config-based method; however, the `publish_image` job uses yaml anchors, & env vars set in the original version are overridden by a separate environment section in each image-building job
(fully adopting 2.1 functionality w/ parameterized jobs would probably fix this...)
> fix env vars

- .circleci/config.yml
- README.md
- shared/images/build.sh
- shared/images/goss.yaml
This PR relates to https://github.com/circleci/circleci-images/issues/106
as part of the process of finally adding some more robust testing to images, we need a way to build & test images that aren't on the `staging` or `master` branches, as most development happens on feature branches. i've created a [ccitest docker hub org](http://hub.docker.com/r/ccitest), and modified the code here to push to that org for all non-`staging` or `master` branch commits
the code (most changes are in `build.sh`) is a bit messy & should be improved but does function
since the `ccitest` org will not track 1 branch like `ccistaging` or `circleci`, but rather all non-`staging` or `master` branches, we want to be able to see from a tag pushed to `ccitest` which branch/commit it came from. however, we also need …
> Add test env

- php/generate-images
This PR relates to an issue where PHP 7.3 images can't install xdebug.
> Support xdebug in PHP 7.3

- .circleci/config.yml
- README.md
- shared/images/build.sh
sometimes we get PRs from community members, like https://github.com/circleci/circleci-images/pull/304, which is awesome!
but the way the repo is currently configured, most of our jobs fail for forked PRs b/c they depend on being able to hit external circleci resources, & we don't give forked PRs access to the requisite creds (for good reason!).
this PR makes some changes to our build/push infrastructure to skip certain steps in certain jobs/scripts if a particular workflow is running from a forked PR. this way, contributors from the community can see images build and test in their CircleCI jobs.
control flow in `build.sh` & `config.yml` to check for forked PR status, & if so, skip anything that would fail, while running everything else normally
> Improve forked flow

- .circleci/config.yml
- .gitignore
- Makefile
- postgres/generate-images
some final changes to ensure that community-submitted PRs (like https://github.com/circleci/circleci-images/pull/306) can build & test as expected
also use the updated compare-url orb, which has a job instead of a command, so it only needs to run once, in one container, to have results used by all image-publishing jobs
as usual, this PR ballooned out of control as i kept seeing additional opportunities to improve things / fix bugs:
- the Workflows job order has been restructured: compare-url orb job runs first, then we run dockerfiles & automated builds simultaneously, then refresh tool cache, then all image jobs. we can use the results of the compare url orb to decide whether or not to proceed w/ pushing to circleci-dockerfiles or example-images (no need to clutter them up with identical …
> Fix forked prs 2

- Makefile
- erlang/generate-images
- erlang/goss.yaml
Official Erlang images lack certain packages necessary for all features of CircleCI to work. I was hoping this could be included in the CircleCI set of images and then I can use those for the rebar3 orb, https://circleci.com/orbs/registry/orb/tsloughter/rebar3 -- I might get this moved to an Erlang namespace eventually since we have rebar3 under the Erlang organization on github.
Adds images for Erlang. I'd like alpine to be included but right now it looks like there isn't a way to get the generated images to use `apk` instead of `apt` in install commands that are added to the Dockerfile.
> add Erlang images

- .circleci/config.yml
image-building jobs currently depend on `CIRCLE_COMPARE_URL` having been reconstructed, so without this change, our daily `cron` workflow on `master` will fail, as the env var won't exist
we always build all images on master anyway, so we don't technically _need_ to reconstruct `CIRCLE_COMPARE_URL`, but this is the simplest fix & the job only takes a few seconds, so i think it's fine for now
> run compare-url job on cron workflow, too

- android/Dockerfile.m4
This PR relates to the issue raised in discuss.circleci.com [Android Platform 28 SDK license not accepted](https://discuss.circleci.com/t/android-platform-28-sdk-license-not-accepted/27768).
Builds relying on Android images are failing as not all the Android SDK licenses are accepted.
```
Failed to install the following Android SDK packages as some licences have not been accepted.
build-tools;28.0.2 Android SDK Build-Tools 28.0.2
To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html
```
This is because the default operations in the [circleci docker …
> Fixing Android Platform 28 SDK license not accepted

- android/Dockerfile.m4
This PR relates to license agreements not accepted when Android compile version is set to 27. Attempts to use Build Tools 28.0.2.
This is an extension to https://github.com/circleci/circleci-images/pull/318
Adding in missing Build Tools versions from 28
> Adding Android Build Tools 28.0.1 and 28.0.2

- shared/images/Dockerfile-basic.template
This PR relates to #324 .
This change removes the filter from the Docker download script. Without this change, no stable versions of Docker newer than 18.06.1 will ever be installed in a CircleCI image.
I tested this change by first shelling into an existing image and running the modified line to update docker, then adding it to my own CircleCI config.yml as a build step. This change works in both cases.
I have simply removed the '-ce' from the grep filter that filters through the stable releases of Docker.
> Dont filter Docker releases using old '-ce' suffix

- .circleci/config.yml
Fully disable the compare-url "feature" for now so that `master` can build successfully.
> Fully disable compare-url from builds.

- .circleci/config.yml
Fix the PHP job.
The parallelism number of 20 is no longer working for us. There wasn't a tag to build in some of the containers. Dropping it to 18 didn't seem to work so I settled on 16, which has consistently passed builds.
> Lower parallelism for PHP job so it doesn't fail.

- openjdk/generate-images
- shared/images/generate.sh
This PR fixes the OpenJDK job by being more specific with which Docker tags we use.
The OpenJDK Docker Team changed their base OS variants. With v11, they introduced more Oracle/Oracle Linux variants. Those images aren't Debian-based and thus don't have `apt-get`. Our build script installs tools such as Apache Ant via Apt-Get thus is failing.
With v12, Oracle Linux has become their default base distro, resulting in even more tags that we can't build.
From what I've seen, there's bases of Oracle Linux, Windows Core, Alpine, Debian Jessie, and Debian Stretch. Since Jessie is very old, this PR will only pull the `stretch` tags. Come mid-2019, we'll also want to add `buster` as well which will be the Debian 10 release which the OpenJDK Docker Team is planning to use.
> Fix OpenJDK Builds

- .circleci/config.yml
- [ X] I've updated the documentation if necessary.
in disabling the `circle-compare-url` orb logic, we actually stopped pushing to the [circleci-dockerfiles](https://github.com/circleci-public/circleci-dockerfiles) or [example-images](https://github.com/circleci-public/example-images) repositories entirely—but actually, if it's disabled, we want to just run those jobs to completion all the time
rearrange logic of these jobs to use the compare-url orb if its job is called in a given workflow, otherwise just proceed with the jobs as usual
> fix compare-url logic for dockerfiles / example images

- shared/images/Dockerfile-basic.template
This PR fixes the `buildpack-deps` image/job that's failing. It also adds a missing repository (that I removed in #368) that isn't needed in our other images but could be useful to have anyway since it was initially present.
> Fix buildpack-deps.

- android/Dockerfile.m4
This PR doesn't have a corresponding issue, and is just a followup to my previous PR (#314) which I had to close because I deleted my fork prematurely.
This new version of Ruby was released at the end of January, and includes a large number of speed gains and new low-level features I'd like to be able to use, as I imagine many others would.
I would understand if this is too much of a jump, but since 2.6.1 is semver-backwards-compatible with 2.4.3, I would think it shouldn't be too scary.
I have tested this locally with a full `fastlane` suite on a React-Native codebase. Fastlane is a common Ruby-based build script in Android, and it worked fine. `make` exits successfully.
`s/2\.4\.3/2\.6\.1/g` in `Dockerfile.mk`. See diff. (It's a two-line substitution.)
See also #314.
CC @felicianotech …
> android: Update Ruby to v2.6.1

- mongo/resources/Dockerfile-basic.template
- mongo/resources/Dockerfile-ram.template
The `--noprealloc` flag has been deprecated in MongoDB for awhile now. Starting with the v4.1 release, it's now erroring out causing builds to fail for users. This PR removes this flag.
Fixes #371.
https://docs.mongodb.com/manual/reference/program/mongod/#cmdoption-mongod-noprealloc
> mongo: Remove deprecated --noprealloc flag.

- mongo/resources/Dockerfile-basic.template
- mongo/resources/Dockerfile-ram.template
This is a continuation of #383. MongoDB v4.1.x still isn't starting.
> mongo: Fix MongoDB v4.1.x startup.

- mongo/resources/Dockerfile-ram.template
This PR relates to #387.
Currently `mongo:*-ram` images aren't able to start because the dbpath directory (in shared memory) doesn't exist. 
Alter the `mongo:*-ram` template to create the (shared memory) dbpath at container run-time instead of trying to create it at build time (reverting part of 93920c60a11c41a074957904d9e0b69badcd9dba). 
I was not able to get the tests to run on my system (I am not sure how to construct the `circleci-bundles` folder structure), but I manually started each generated `mongo:*-ram` image to confirm that it started correctly.
> Create mongo-ram shared memory dbpath on container start.

- php/generate-images
This PR relates to moving away from a beta version of xdebug.
Moving to the latest version of xdebug available for PHP 7.3.
> Move away from the beta version of xdebug in PHP 7.3

- rust/generate-images
- rust/goss.yaml
musl is a tiny libc implementation and helps create cross-distro static binaries.
A common use-case in Rust is to use [musl](https://www.musl-libc.org/) as a tiny `libc` implementation to build static binaries without any share library linkage, similar to the binaries that Golang produces by default. In order to compile these binaries, the following criteria should be met:
1. `rustup target add x86_64-unknown-linux-musl`: add the toolchain
2. install `musl` to add a `musl-gcc` binary for actually doing the compilation.
Since `circleci/rust` does not do any Rust-specific customizations to the base image, I have not added the toolchain but I have installed the musl packages to make static binary compilation possible.
This change simply installs the `musl`, `musl-dev`, and `musl-tools` into …
> Install Musl for Rust Images

- android/Dockerfile.m4
- openjdk/generate-images
- php/generate-images
- python/generate-images
This avoids including the apt-get and pip installation cache files in the Docker image layers, which follows Dockerfile best practices.
This should reduce the size of the Python images for example by about 20 to 30 MB (estimated), which I imagine is significant when multiplied by all pulls.
Background for apt-get:
* https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#apt-get
> Avoid installation caches in image layers

- .circleci/config.yml
- node/generate-images
- shared/images/Dockerfile-browsers-legacy.template
- shared/images/Dockerfile-browsers.template
Updates OpenJDK from v8 to v11. Also removes the code for supporting
Debian Jessie and Ubuntu Trusty as neither are supported.
The Bash if blocks may need to be put back if other distros are having
issues with OpenJDK 11.
Fixes #381.
> Updates Java in the -browsers variant to v11.

- shared/images/Dockerfile-browsers-legacy.template
- shared/images/Dockerfile-browsers.template
Chromedriver installs are causing frequent build failures right now. That's what most of the `master` branch's latest failures are.
Specifically, the `curl` commands tend to fail. This PR increases timeout time and tries to improve the situation. If this problem continues, we may need to host our own binaries for Chromedriver or pull them from a proxied location that's more reliable.
> Fix transient Chromedriver errors.

- shared/images/Dockerfile-basic.template
Fixes #420 
After the `circleci` user is created, this PR manually creates the `$HOME/bin` and `$HOME/.local/bin` directories. This allows the `$HOME/.profile` script to automatically add those directories to the `PATH`.
> Set local/bin for circleci user.

- rust/generate-images
The official Rust Docker image does not install `rustfmt`. The tool is, however, often used in CI workflows
to check formatting of submitted changes.
Tested by building the image and verifying that `rustfmt` and `cargo fmt` commands are usable.
Added `RUN rustup component add rustfmt` as an image customization step.
> rust: install rustfmt

- android/Dockerfile.m4
Adds the point release update to build-tools v29.
Prompted by: https://github.com/CircleCI-Public/circleci-dockerfiles/pull/19
> Android: Add build-tools-29.0.1.

- openjdk/generate-images
OpenJDK v8 images (`8-jdk-`) weren't building. This was because of upstream changing their base from Debian to Oracle and our reaction to it. This image was dropped in the switch. Restoring these builds.
> OpenJDK: Reenable v8 build for old image.

- postgres/generate-images
- postgres/resources/Dockerfile-postgis.template
Enables the PostgreSQL 12 images now that v12 has reached a stable
release. Also preemptively disables v13 images as they'll be in various
stages of completion until its eventual release.
Fixes #441
> Enable PostgreSQL 12 images.

- .circleci/config.yml
The CircleCI envar `CIRCLE_USERNAME` now doesn't populate on scheduled workflows. When this happens, our job to generate Dockerfiles and push to GitHub is failing.
This PR fixes this by manually setting an email and username when the variable is empty.
> Fix git user setting.

- android/generate-images
- shared/images/generate-node.sh
With Node.js v12 becoming the new LTS, the build system for our `-node` variants failed.
This was due to a simple regex problem. The tag `lts` is no longer last in the list of tags. This fix allows the tag to be somewhere in the list that's not last.
> Fix node lts 12

- postgres/generate-images
Disables the building of Alpine-based PostgreSQL images. They're too unstable for us. The second largest reason for build failures is Alpine.
> Disable PostgreSQL Alpine builds.

- postgres/resources/Dockerfile-basic.template
Reverts an upstream change that caused breaking builds. https://github.com/docker-library/postgres/pull/658
> Revert password requirement from upstream.

- postgres/generate-images
- postgres/resources/Dockerfile-postgis.template
Postgres 13 is GA as of September 24th, 2020 - https://www.postgresql.org/about/news/postgresql-13-released-2077/
This PR follows the pattern of https://github.com/circleci/circleci-images/pull/442 when Postgres 12 was officially added. The logic for determining which PostGIS version to use now checks for versions greater than or equal to 12 for forward compatibility. (PostGIS 2.x is not supported on PG 13 at all)
> Adds support for Postgres 13

- mysql/resources/Dockerfile-basic.template
Bring the changes from https://github.com/circleci/circleci-images/pull/540 into the main branch.
As described in https://github.com/docker-library/mysql/issues/750#issuecomment-801792228, `MYSQL_USER=root` is redundant and now causes an error, so we should remove it.
> Remove MYSQL_USER ENV (#540)

- android/Dockerfile-ndk.template
This PR relates to <issue>.
The Android NDK image for API version 30 does not support NDK API version 30.
Bump NDK version to support NDK 30 APIs.
> Update Android NDK to r21e

- android/Dockerfile.m4
- Build tools 30.0.3 are not available when fetching the android image
- Add support for Android build tools 30.0.3
> Android: add support for build tools 30.0.3

- openjdk/generate-images
sbt can't be run from the root dir as-is. This adds a flag so that it doesn't fail.
This fix was borrowed from this PR: https://github.com/circleci/circleci-images/pull/549/files
Upstream change: https://github.com/sbt/sbt/pull/5112
There was also a second issue with the newly added Oracle Linux upstream base images. This was fixed as well.
> Fix OpenJDK issue with sbt

- openjdk/generate-images
An Early Access (EA)(unreleased) build is causing problems. Disabling it.
The other jobs that failed are unrelated. Other PRs will be opened for them, as needed.
> Disable early access builds for OpenJDK
