circleci/circleci-images

- shared/images/build.sh
Add better logging of progress.
> Remove images after creation to save disk space

- android/Dockerfile.m4
- php/generate-images
- ruby/generate-images
- shared/images/Dockerfile-basic.template
- shared/images/Dockerfile-browsers.template
- shared/images/generate.sh
- shared/images/manifest
Always enable --fail --location, etc
> Make the curl flags robust

- .circleci/config.yml
- Makefile
- buildpack-deps/generate-images
Based on https://hub.docker.com/r/_/buildpack-deps/
> Add buildpack-deps images

- openjdk/java_helper
Update version matcher to match the new sbt website version.
> fix sbt scraper

- openjdk/generate-images
- php/generate-images
- ruby/generate-images
- shared/images/Dockerfile-basic.template
- shared/images/generate.sh
Add some smoke tests to ensure that we installed the tools we expected, and output their versions in the build output.
Also, deprecate OpenJDK 6 and 7.  They are EOL and some tools (e.g. Ant) no longer support them.
> Various Fixes

- shared/images/Dockerfile-basic.template
- shared/images/Dockerfile-browsers.template
Docker binary links have changed
Also, added some smoke test and version for browsers as well.
> Fix docker links

- .circleci/config.yml
- Makefile
- jruby/generate-images
This PR relates to CIRCLE-6361.
> [CIRCLE-6361] Add official JRuby images

- README.md
> Update README with where to find Dockerfiles

- android/Dockerfile.m4
Install Ruby as a user rather than system wide, install `bundler`, and ensure that users can install gems without `sudo`.
> Set ruby paths correctly

- android/Dockerfile.m4
> Install libcurl-dev

- postgres/resources/Dockerfile-postgis-ram.template
- postgres/resources/Dockerfile-postgis.template
This PR relates to https://github.com/circleci/circleci-images/issues/84
> Non-Alpine PostGIS fix

- android/Dockerfile.m4
> Add Android build tools v26.0.2

- .circleci/config.yml
Build the `production` branch on a schedule.
> Scheduled builds

- README.md
- docs/IMAGES.md
> Some copy edits.

- .circleci/config.yml
- Makefile
- mariadb/generate-images
- mariadb/resources/Dockerfile-basic.template
- mariadb/resources/Dockerfile-ram.template
- shared/images/manifest
Fixes #103 
Propose a MariaDB bundle.
> Add MariaDB bundle.

- openjdk/java_helper
- php/generate-images
- postgres/resources/Dockerfile-postgis.template
- shared/images/Dockerfile-browsers.template
- shared/images/refresh-tools-cache
Grab-bag of fixes to get image building green.  Review individual commits independently.
> Fixes 20171203

- shared/images/Dockerfile-basic.template
PHP images were missing gpg.  Added it along with curl and wget because
many folks (including our tools) expect them to be present.
This caused the failure in https://circleci.com/gh/circleci/circleci-images/3510 .
> Ensure gpg is installed

- postgres/resources/Dockerfile-postgis.template
Postgis scripts need to be executables 
This PR relates to #122
> postgis scripts need to be executables

- postgres/resources/Dockerfile-postgis.template
> postgis: entrypoint needs read bits too

- .circleci/config.yml
> fix git errors

- .circleci/config.yml
- redis/generate-images
- redis/resources/Dockerfile-basic.template
Add Redis images that are configured not to perform any disk IO
operation.  In CI with ephemeral nodes, persistence and data recovery is
over-rated for data stores in the general case.
> Add Redis images

- android/Dockerfile.m4
> Add new BT 27.0.1, 27.0.2, 27.0.3

- android/Dockerfile.m4
> Update Ruby within Android image.

- php/generate-images
This PR relates to https://github.com/circleci/circleci-images/issues/155
> xdebug support for 5.6

- clojure/generate-images
https://github.com/circleci/circleci-images/issues/93
> Clojure receives node variants

- .circleci/config.yml
- [ X ] I've run `make` from the root directory to see all Dockerfiles are created successfully.
- [ X ] I've updated the documentation if necessary.
This PR relates to <issue>.
> push staging images to new org

- .circleci/config.yml
> use ricardos docker image w/aws since aws broke their pip install

- .circleci/config.yml
Installing a specific version of awscli to avoid dependency issues.
> awscli==1.14.17

- shared/images/README-basic.template
- shared/images/README-service.template
This PR relates to https://github.com/circleci/circleci-images/issues/141.
- link to circleci-dockerfiles repo in readmes
- polish up language/markdown
> polish up readmes

- shared/images/README-basic.template
- shared/images/README-service.template
> update readmes a bit more

- rust/generate-images
> Rust image

- .circleci/config.yml
> Rust in production

- README.md
- shared/images/README-basic.template
This PR relates to https://github.com/circleci/circleci-images/issues/86.
We need to give our users a heads up we're going to upgrade Firefox.
> Firefoxreadmes

- android/Dockerfile.m4
This PR relates to #234 .
properly extract android NDK
> Fix android ndk

- .circleci/config.yml
- README.md
- android/Dockerfile.m4
- shared/images/README-basic.template
merge staging into master
android NDK issue is fixed, also get updated READMEs (documenting future Firefox upgrades) into master
> merge updated staging into master

- shared/images/Dockerfile-browsers.template
This change is necessary to fix the syntax for proper sh support.
> Syntax fix to accommodate sh

- shared/images/Dockerfile-browsers.template
Some images are failing to build with the current script so we're removing the validation with the .asc file for now.
> TODO: verify the integrity of the downloaded file

- postgres/resources/Dockerfile-basic.template
- [] I've updated the documentation if necessary. (will be doing this before merge to master)
https://discuss.circleci.com/t/circleci-postgres-image-suddenly-causing-problems-role-postgres-not-found
> remove PG user due to upstream changes

- golang/generate-images
This PR relates to https://github.com/circleci/circleci-images/issues/259
We are now installing `gotestsum v0.3.1`(https://github.com/gotestyourself/gotestsum/releases) in our Golang images in /go/bin.
> Introduce gotestsum for the golang images

- .github/CODEOWNERS
> Remove self from codeowners 😢

- README.md
- golang/generate-images
- postgres/resources/Dockerfile-basic.template
- shared/images/README-basic.template
- shared/images/README-service.template
let's get latest changes from staging into master:
https://github.com/circleci/circleci-images/pull/267
https://github.com/circleci/circleci-images/pull/268
> Merge recent changes into master

- .github/CODEOWNERS
- shared/images/generate-node.sh
This PR relates to an issue where images are not building from the correct base image.
Also adding a `whoami` to verify the `circleci` user exists before proceeding.
> Remove the second FROM line that is breaking images

- .circleci/config.yml
2.1 config processing is turned on for this repo, so our logic that determines when to build or not build images is broken
add compare URL orb to reconstruct `CIRCLE_COMPARE_URL` so our build logic functions again
> add compare url orb

- README.md
- golang/generate-images
- shared/images/README-basic.template
- shared/images/README-service.template
- shared/images/example.sh
a couple of minor issues prevented fixes for the missing `circleci` user from being successfully shipped to all our images. these issues have now been patched in staging.
> merge fixes for a couple of bugs adjacent to incident

- .circleci/config.yml
bump parallelism for slow image-building jobs, also put them in alphabetical order so it's not such a nightmare to find things
> bump parallelism, alphabetize image jobs

- .circleci/config.yml
we already merged this to master (b/c we want the changes in immediately, whereas staging has some changes we need to sit on for a bit), want to merge to staging to make sure they stay relatively in sync
> Always build all nightlies

- .circleci/config.yml
- shared/images/build.sh
- shared/images/goss.yaml
This PR relates to #106 & #209 
adding a simple `docker run` test w/ `dgoss` in between building & pushing of images
> add initial `docker run` testing

- .circleci/config.yml
This PR relates to building Erlang images. The prior PR did not add a job to build the images in question.
> Erlang jobs for CircleCI

- .circleci/config.yml
- android/Dockerfile.m4
https://github.com/circleci/circleci-images/pull/318
https://github.com/circleci/circleci-images/pull/319
> Fix Android SDK => master

- README.md
some folks don't know to check discuss for image announcements
add info to readme re: where to look for info on changes to images
> add info on discuss announcements

- python/generate-images
> Add poetry to Python image

- shared/images/README-basic.template
- shared/images/README-service.template
we've added info about to discuss to this repo's readme; now let's add it to the readmes that get sent to docker hub
add info from repo readme to our readme templates
> add discuss info to templates for docker hub readmes

- .circleci/config.yml
- shared/images/Dockerfile-browsers-legacy.template
- shared/images/Dockerfile-browsers.template
This PR relates to <issue>.
https://circleci.zendesk.com/agent/tickets/47945
tested in docker
updated release number to new versioning by Google
> Update chromedriver uri

- .circleci/config.yml
https://github.com/circleci/circleci-images/pull/359
> Lower parallelism for PHP job so it doesn't fail => master

- .circleci/config.yml
- openjdk/generate-images
- shared/images/generate.sh
https://github.com/circleci/circleci-images/pull/361
> Fix OpenJDK Builds => master

- .circleci/config.yml
https://github.com/circleci/circleci-images/pull/363
> fix compare-url logic for dockerfiles / example images => master

- shared/images/Dockerfile-browsers-legacy.template
- shared/images/Dockerfile-browsers.template
This PR fixes the mixed indentation that was introduces by https://github.com/circleci/circleci-images/pull/368
> Fix mixed indentation in templates

- .github/CODEOWNERS
- shared/images/Dockerfile-basic.template
- shared/images/Dockerfile-browsers-legacy.template
- shared/images/Dockerfile-browsers.template
https://github.com/circleci/circleci-images/pull/373
> Fix buildpack-deps => master

- shared/images/Dockerfile-basic.template
This PR relates to <https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=839155>, and should resolve #375 (see there for discussion).
> Make sure PATH includes ~/.local/bin

- mongo/resources/Dockerfile-ram.template
https://github.com/circleci/circleci-images/pull/392
> Move away from the beta version of xdebug in PHP 7.3 => master

- .circleci/config.yml
- android/Dockerfile.m4
- android/generate-images
- postgres/generate-images
- postgres/resources/Dockerfile-postgis.template
- rust/generate-images
- rust/goss.yaml
- shared/images/Dockerfile-basic.template
- shared/images/generate-node.sh
- fix node variants
- fix postgis
- add make
- Android API 29
- musl packages in Rust
> Merge Staging to Master - June 17th

- android/Dockerfile.m4
> Android: Avoid easy_install with Apt.

- golang/generate-images
Updates gotestsum in the Go image.
> Go: Update gotestsum to v0.3.5.

- android/Dockerfile.m4
- golang/generate-images
- rust/generate-images
- shared/images/Dockerfile-basic.template
- shared/images/Dockerfile-browsers-legacy.template
- shared/images/Dockerfile-browsers.template
None of these changes should be specifically breaking and all are documented for the September Discuss post.
> Promote Recent August Commits to Master

- shared/images/Dockerfile-basic.template
Fix for bug found by @kirk-clover.
> Fix local bin mkdir.

- android/Dockerfile.m4
Add the latest point release for the Android build tools.
> Android: build-tools-29.0.2

- postgres/generate-images
- postgres/resources/Dockerfile-postgis.template
Promote PostgreSQL 12 changes to `master`.
> Enable PostgreSQL 12 images. (#442)

- postgres/generate-images
> Disable PostgreSQL Alpine builds. (#463)

- golang/generate-images
https://github.com/gotestyourself/gotestsum/releases/tag/v0.4.2
> golang: Update gotestsum to pick up bug fixes
